### ISSUE TITLE
Up/Down Buttons

### ISSUE THREAD

**Issue by zspri** [iamunknown2/dragon-drop-remake#1]
When pressing the up and down buttons, if the element is at the top or bottom of the list, then it disappears.

**Comment by iamunknown2** [comment]
Yeah, it turns up as "undefined". I'll try to fix that by hiding the button if it's the top or bottom element.

**Comment by iamunknown2** [comment]
Fixed with https://github.com/iamunknown2/dragon-drop-remake/commit/2f7120c32211b0f65f1e24d03acf051353c841fc. Closing.
